apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  "server.properties": |-
    {{- tpl ( .Files.Get "files/server.properties" | nindent 4 ) .}}
  "resources.tf": |-
    {{ .Files.Get "files/resources.tf" | nindent 4 }}
