apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka.fullname" . }}-terrform
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Mi
