replicaCount: 3

image:
  repository: vitalibo/kafka
  pullPolicy: IfNotPresent
  tag: ""

terraformImage:
  repository: hashicorp/terraform
  pullPolicy: IfNotPresent
  tag: "0.14.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9092

resources:
#  limits:
#    cpu: 100m
#    memory: 1024Mi
#  requests:
#    cpu: 100m
#    memory: 1024Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

podAnnotations: { }

podSecurityContext: { }

securityContext: { }
