apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  clusterIP: None
  ports:
    - port: 2888
      targetPort: server
      name: server
    - port: 3888
      targetPort: leader-election
      name: leader-election
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
